id: PAEE31885
initial_creation_type: ocr
source_metadata:
  volumes:
    aab36c53971541b28755f03fa925e2aa:
      base_file: v066.txt
      image_group_id: I1PD95911
      title: འཕགས་པ་བློ་གྲོས་མི་ཟད་པས་བསྟན་པ་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1470
      volume_number: 66
